name: Kernel CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install required packages
      run: |
        sudo apt update
        sudo apt install -y sed xz-utils wget curl build-essential git libssl-dev flex bison bc python2 python-is-python3 device-tree-compiler gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi clang llvm lld ccache

    - name: Add KernelSU
      run: curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s main

    - name: Build config
      run: make -j$(nproc --all) O=out ARCH=arm64 SUBARCH=arm64 DTC_EXT=dtc LLVM=1 LLVM_IAS=1 LD=ld.lld AR=llvm-ar NM=llvm-nm STRIP=llvm-strip OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump READELF=llvm-readelf HOSTCC=clang HOSTCXX=clang++ HOSTAR=llvm-ar HOSTLD=ld.lld CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-gnueabi- CROSS_COMPILE_COMPAT=arm-linux-gnueabi- CC="ccache clang" vayu_user_defconfig

    - name: Build kernel
      run: make -j$(nproc --all) O=out ARCH=arm64 SUBARCH=arm64 DTC_EXT=dtc LLVM=1 LLVM_IAS=1 LD=ld.lld AR=llvm-ar NM=llvm-nm STRIP=llvm-strip OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump READELF=llvm-readelf HOSTCC=clang HOSTCXX=clang++ HOSTAR=llvm-ar HOSTLD=ld.lld CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-gnueabi- CROSS_COMPILE_COMPAT=arm-linux-gnueabi- CC="ccache clang" all

    - name: Download libufdt
      run: git clone -q --depth=1 https://android.googlesource.com/platform/system/libufdt

    - name: Download AnyKernel
      run: |
        git clone -q --depth=1 https://github.com/chiteroman/AnyKernel3-vayu.git anykernel
        rm -rf anykernel/.git*

    - name: Copy Image
      run: cp -f out/arch/arm64/boot/Image anykernel/Image

    - name: Copy dtb
      run: find out/arch/arm64/boot/dts/qcom -name 'sm8150*.dtb' -exec cat {} + > anykernel/dtb

    - name: Make AOSP dtbo
      run: python3 libufdt/utils/src/mkdtboimg.py create anykernel/dtbo.img --page_size=4096 out/arch/arm64/boot/dts/qcom/vayu-sm8150-overlay.dtbo

    - name: Upload kernel
      uses: actions/upload-artifact@v4
      with:
        name: kernel_KSU
        path: 'anykernel/*'
        compression-level: 9

    - name: Disable KernelSU
      run: scripts/config --file out/.config -e CONFIG_KSU

    - name: Build kernel with KSU
      run: make -j$(nproc --all) O=out ARCH=arm64 SUBARCH=arm64 DTC_EXT=dtc LLVM=1 LLVM_IAS=1 LD=ld.lld AR=llvm-ar NM=llvm-nm STRIP=llvm-strip OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump READELF=llvm-readelf HOSTCC=clang HOSTCXX=clang++ HOSTAR=llvm-ar HOSTLD=ld.lld CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-gnueabi- CROSS_COMPILE_COMPAT=arm-linux-gnueabi- CC="ccache clang" all

    - name: Copy Image
      run: cp -f out/arch/arm64/boot/Image anykernel/Image

    - name: Upload kernel
      uses: actions/upload-artifact@v4
      with:
        name: kernel
        path: 'anykernel/*'
        compression-level: 9

    - name: Modify dtbo for MIUI 14+
      run: |
        sed -i 's/<70>/<695>/g'   arch/arm64/boot/dts/qcom/xiaomi/overlay/common/display/dsi-panel-j20s-36-02-0a-lcd-dsc-vid.dtsi
        sed -i 's/<154>/<1546>/g' arch/arm64/boot/dts/qcom/xiaomi/overlay/common/display/dsi-panel-j20s-36-02-0a-lcd-dsc-vid.dtsi
        sed -i 's/<70>/<695>/g'   arch/arm64/boot/dts/qcom/xiaomi/overlay/common/display/dsi-panel-j20s-42-02-0b-lcd-dsc-vid.dtsi
        sed -i 's/<154>/<1546>/g' arch/arm64/boot/dts/qcom/xiaomi/overlay/common/display/dsi-panel-j20s-42-02-0b-lcd-dsc-vid.dtsi

    - name: Build dtbs (for MIUI 14+)
      run: make -j$(nproc --all) O=out ARCH=arm64 SUBARCH=arm64 DTC_EXT=dtc LLVM=1 LLVM_IAS=1 LD=ld.lld AR=llvm-ar NM=llvm-nm STRIP=llvm-strip OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump READELF=llvm-readelf HOSTCC=clang HOSTCXX=clang++ HOSTAR=llvm-ar HOSTLD=ld.lld CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-gnueabi- CROSS_COMPILE_COMPAT=arm-linux-gnueabi- CC="ccache clang" dtbs

    - name: Make dtbo for MIUI 14+
      run: python3 libufdt/utils/src/mkdtboimg.py create out/dtbo-miui14.img --page_size=4096 out/arch/arm64/boot/dts/qcom/vayu-sm8150-overlay.dtbo

    - name: Upload dtbo for MIUI 14+
      uses: actions/upload-artifact@v4
      with:
        name: dtbo-miui14
        path: 'out/dtbo-miui14.img'
        compression-level: 9
